VERSION 5.00
Begin VB.Form Form1 
   Caption         =   "ﬁ«„Ê”"
   ClientHeight    =   1620
   ClientLeft      =   60
   ClientTop       =   345
   ClientWidth     =   4680
   LinkTopic       =   "Form1"
   MaxButton       =   0   'False
   RightToLeft     =   -1  'True
   ScaleHeight     =   1620
   ScaleWidth      =   4680
   StartUpPosition =   3  'Windows Default
   Begin VB.CommandButton Command1 
      Caption         =   " —Ã„"
      Height          =   495
      Left            =   3120
      TabIndex        =   2
      Top             =   600
      Width           =   1455
   End
   Begin VB.TextBox Text2 
      Height          =   375
      Left            =   120
      TabIndex        =   1
      Top             =   1200
      Width           =   4455
   End
   Begin VB.TextBox Text1 
      Height          =   375
      Left            =   120
      TabIndex        =   0
      Top             =   120
      Width           =   4455
   End
End
Attribute VB_Name = "Form1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Private Sub Command1_Click()
Select Case Text1.Text
Case "one"
Text2.Text = "Ê«Õœ"
Case "two"
Text2.Text = "«À‰«‰"
Case "three"
Text2.Text = "À·«À…"
Case "four"
Text2.Text = "√—»⁄…"
Case "five"
Text2.Text = "Œ„”…"
Case "six"
Text2.Text = "” …"
Case "seven"
Text2.Text = "”»⁄…"
Case "eight"
Text2.Text = "À„«‰Ì…"
Case "nine"
Text2.Text = " ”⁄…"
Case "ten"
Text2.Text = "⁄‘—…"
Case "name"
Text2.Text = "«”„"
Case "hello"
Text2.Text = "√Â·«"
Case "plane"
Text2.Text = "ÿ«∆—…"
Case "kite"
Text2.Text = "ÿ«∆—… “—ﬁÌ…"
Case "car"
Text2.Text = "”Ì«—…"
Case "bus"
Text2.Text = "Õ«›·…"
Case "doll"
Text2.Text = "œ„Ì…"
Case "house"
Text2.Text = "»Ì "
Case "boy"
Text2.Text = "Ê·œ"
Case "girl"
Text2.Text = "»‰ "
Case "robot"
Text2.Text = "—Ã· ¬·Ì"
Case "car"
Text2.Text = "”Ì«—…"
Case "bag"
Text2.Text = "ÕﬁÌ»…"
Case "shoe"
Text2.Text = "Õ–«¡"
Case "box"
Text2.Text = "’‰œÊﬁ"
Case "pencil"
Text2.Text = "ﬁ·„ —’«’"
Case "rubber"
Text2.Text = "„„Õ«…"
Case "cat"
Text2.Text = "ﬁÿ…"
Case "look"
Text2.Text = "«‰Ÿ—"
Case "apple"
Text2.Text = " ›«Õ…"
Case "owl"
Text2.Text = "»Ê„…"
Case "insect"
Text2.Text = "Õ‘—…"
Case "ball"
Text2.Text = "ﬂ—…"
Case "dog"
Text2.Text = "ﬂ·»"
Case "umbrella"
Text2.Text = "„Ÿ·…"
Case "parrot"
Text2.Text = "»»€«¡"
Case "elephant"
Text2.Text = "›Ì·"
Case "purple"
Text2.Text = "»‰›”ÃÌ"
Case "blue"
Text2.Text = "√“—ﬁ"
Case "green"
Text2.Text = "√Œ÷—"
Case "yellow"
Text2.Text = "√’›—"
Case "red"
Text2.Text = "√Õ„—"
Case "orange"
Text2.Text = "»— ﬁ«·Ì"
Case "color"
Text2.Text = "·Ê‰"
Case "balloon"
Text2.Text = "»«·Ê‰"
Case "bear"
Text2.Text = "œ»"
Case "lion"
Text2.Text = "√”œ"
Case "monkey"
Text2.Text = "ﬁ—œ"
Case "zebra"
Text2.Text = "Õ„«— ÊÕ‘Ì"
Case "sunny"
Text2.Text = "„‘„”"
Case "dinosaur"
Text2.Text = "œÌ‰«’Ê—"
Case "little"
Text2.Text = "’€Ì—"
Case "big"
Text2.Text = "ﬂ»Ì—"
Case "candle"
Text2.Text = "‘„⁄…"
Case "cake"
Text2.Text = "ﬂ⁄ﬂ…"
Case "hat"
Text2.Text = "ÿ«ﬁÌ…"
Case "present"
Text2.Text = "ÂœÌ…"
Case "party"
Text2.Text = "Õ›·…"
Case "birthday"
Text2.Text = "⁄Ìœ „Ì·«œ"
Case "monkey"
Text2.Text = "ﬁ—œ"
Case "clown"
Text2.Text = "„Â—Ã"
Case "happy"
Text2.Text = "”⁄Ìœ"
Case "sad"
Text2.Text = "Õ“Ì‰"
Case "friend"
Text2.Text = "’œÌﬁ"
Case "hand"
Text2.Text = "Ìœ"
Case "arm"
Text2.Text = "–—«⁄"
Case "leg"
Text2.Text = "—Ã·"
Case "foot"
Text2.Text = "ﬁœ„"
Case "frog"
Text2.Text = "÷›œ⁄"
Case "pen"
Text2.Text = "ﬁ·„"
Case "hen"
Text2.Text = "œÃ«Ã…"
Case "fish"
Text2.Text = "”„ﬂ…"
Case "bird"
Text2.Text = "ÿ«∆—"
Case "rabbit"
Text2.Text = "√—‰»"
Case "boat"
Text2.Text = "ﬁ«—»"
Case "train"
Text2.Text = "ﬁÿ«—"
Case "hair"
Text2.Text = "‘⁄—"
Case "eye"
Text2.Text = "⁄Ì‰"
Case "kitchen"
Text2.Text = "„ÿ»Œ"
Case "table"
Text2.Text = "ÿ«Ê·…"
Case "bed"
Text2.Text = "”—Ì—"
Case "sofa"
Text2.Text = "ﬂ‰»…"
Case "head"
Text2.Text = "—√”"
Case "phone"
Text2.Text = "Â« ›"
Case "fridge"
Text2.Text = "À·«Ã…"
Case "chair"
Text2.Text = "ﬂ—”Ì"
Case "duck"
Text2.Text = "»ÿ…"
Case "desk"
Text2.Text = "„ﬂ »"
Case "over"
Text2.Text = "›Êﬁ"
Case "under"
Text2.Text = " Õ "
Case "between"
Text2.Text = "»Ì‰"
Case "book"
Text2.Text = "ﬂ «»"
Case "mouse"
Text2.Text = "›√—"
Case "circle"
Text2.Text = "œ«∆—…"
Case "triangle"
Text2.Text = "„À·À"
Case "square"
Text2.Text = "„—»⁄"
Case "yes"
Text2.Text = "‰⁄„"
Case "no"
Text2.Text = "·«"
Case "grandfather"
Text2.Text = "Ãœ"
Case "grandmother"
Text2.Text = "Ãœ…"
Case "brother"
Text2.Text = "√ŒÊ"
Case "sister"
Text2.Text = "√Œ "
Case "pet"
Text2.Text = "ÕÌÊ«‰ √·Ì›"
Case "zoo"
Text2.Text = "ÕœÌﬁ… ÕÌÊ«‰« "
Case "kangaroo"
Text2.Text = "ﬂ‰€—"
Case "cow"
Text2.Text = "»ﬁ—…"
Case "horse"
Text2.Text = "Õ’«‰"
Case "hill"
Text2.Text = " ·…"
Case "tree"
Text2.Text = "‘Ã—…"
Case "man"
Text2.Text = "—Ã·"
Case "picture"
Text2.Text = "’Ê—…"
Case "teddy"
Text2.Text = "œ»œÊ»"
Case "train"
Text2.Text = "ﬁÿ«—"
Case "bike"
Text2.Text = "œ—«Ã…"
Case "say"
Text2.Text = "ÌﬁÊ·"
Case "fall"
Text2.Text = "Ì”ﬁÿ"
Case "count"
Text2.Text = "Ì⁄œ"
Case "goat"
Text2.Text = "⁄‰“…"
Case "prince"
Text2.Text = "√„Ì—"
Case "princess"
Text2.Text = "√„Ì—…"
Case "castle"
Text2.Text = "ﬁ·⁄…"
Case "clock"
Text2.Text = "”«⁄…"
Case "room"
Text2.Text = "€—›…"
Case "kitchen"
Text2.Text = "„ÿ»Œ"
Case "watch"
Text2.Text = "”«⁄… Ìœ"
Case "bedroom"
Text2.Text = "€—›… ‰Ê„"
Case "blonde"
Text2.Text = "√‘ﬁ—"
Case "mouth"
Text2.Text = "›„"
Case "brown"
Text2.Text = "»‰Ì"
Case "pink"
Text2.Text = "Ê—œÌ"
Case "long"
Text2.Text = "ÿÊÌ·"
Case "tall"
Text2.Text = "ÿÊÌ·"
Case "short"
Text2.Text = "ﬁ’Ì—"
Case "song"
Text2.Text = "√€‰Ì…"
Case "sing"
Text2.Text = "Ì€‰Ì"
Case "egg"
Text2.Text = "»Ì÷…"
Case "tea"
Text2.Text = "‘«Ì"
Case "grey"
Text2.Text = "—„«œÌ"
Case "coffee"
Text2.Text = "ﬁÂÊ…"
Case "night"
Text2.Text = "·Ì·"
Case "ear"
Text2.Text = "√–‰"
Case "crocodile"
Text2.Text = " „”«Õ"
Case "nose"
Text2.Text = "√‰›"
Case "neck"
Text2.Text = "—ﬁ»…"
Case "tail"
Text2.Text = "–Ì·"
Case "giraff"
Text2.Text = "“—«›…"
Case "animal"
Text2.Text = "ÕÌÊ«‰"
Case "inside"
Text2.Text = "œ«Œ·"
Case "trunk"
Text2.Text = "Œ—ÿÊ„"
Case "morning"
Text2.Text = "’»«Õ"
Case "sit"
Text2.Text = "ÌÃ·”"
Case "write"
Text2.Text = "Ìﬂ »"
Case "read"
Text2.Text = "Ìﬁ—√"
Case "draw"
Text2.Text = "Ì—”„"
Case "stand"
Text2.Text = "Ìﬁ›"
Case "open"
Text2.Text = "Ì› Õ"
Case "close"
Text2.Text = "Ì€·ﬁ"
Case "copy"
Text2.Text = "Ì‰”Œ"
Case "banana"
Text2.Text = "„Ê“…"
Case "wood"
Text2.Text = "Œ‘»"
Case "slow"
Text2.Text = "»ÿÌ¡"
Case "fast"
Text2.Text = "”—Ì⁄"
Case "many"
Text2.Text = "ﬂÀÌ—"
Case "much"
Text2.Text = "ﬂÀÌ—"
Case "river"
Text2.Text = "‰Â—"
Case "street"
Text2.Text = "‘«—⁄"
Case "swim"
Text2.Text = "Ì”»Õ"
Case "run"
Text2.Text = "ÌÃ—Ì"
Case "walk"
Text2.Text = "Ì„‘Ì"
Case "jump"
Text2.Text = "Ìﬁ›“"
Case "can"
Text2.Text = "Ì” ÿÌ⁄"
Case "ride"
Text2.Text = "Ì—ﬂ»"
Case "drive"
Text2.Text = "ÌﬁÊœ"
Case "hop"
Text2.Text = "Ìﬁ›“"
Case "fly"
Text2.Text = "ÌÿÌ—"
Case "good"
Text2.Text = "ÃÌœ"
Case "bad"
Text2.Text = "”Ì¡"
Case "sleep"
Text2.Text = "Ì‰«„"
Case "eat"
Text2.Text = "Ì√ﬂ·"
Case "drink"
Text2.Text = "Ì‘—»"
Case "see"
Text2.Text = "Ì—Ï"
Case "leaf"
Text2.Text = "Ê—ﬁ… ‘Ã—"
Case "paper"
Text2.Text = "Ê—ﬁ…"
Case "meat"
Text2.Text = "·Õ„…"
Case "desert"
Text2.Text = "’Õ—«¡"
Case "farm"
Text2.Text = "„“—⁄…"
Case "forest"
Text2.Text = "€«»…"
Case "snake"
Text2.Text = "√›⁄Ï"
Case "camel"
Text2.Text = "Ã„·"
Case "flower"
Text2.Text = "“Â—…"
Case "zebra"
Text2.Text = "Õ„«— ÊÕ‘Ì"
Case "sandwich"
Text2.Text = "”‰œÊÌ‘…"
Case "look"
Text2.Text = "Ì‰Ÿ—"
Case "hear"
Text2.Text = "Ì”„⁄"
Case "cry"
Text2.Text = "Ì»ﬂÌ"
Case "king"
Text2.Text = "„·ﬂ"
Case "kitten"
Text2.Text = "ﬁÿ… ’€Ì—…"
Case "time"
Text2.Text = "Êﬁ "
Case "basket"
Text2.Text = "”·…"
Case "garden"
Text2.Text = "ÕœÌﬁ… «·„‰“·"
Case "home"
Text2.Text = "„‰“·"
Case "play"
Text2.Text = "Ì·⁄»"
Case "woman"
Text2.Text = "«„—√…"
Case "sun"
Text2.Text = "‘„”"
Case "lemon"
Text2.Text = "·Ì„Ê‰"
Case "fruit"
Text2.Text = "›«ﬂÂ…"
Case "bee"
Text2.Text = "‰Õ·…"
Case "black"
Text2.Text = "√”Êœ"
Case "pink"
Text2.Text = "Ê—œÌ"
Case "stand"
Text2.Text = "Ìﬁ›"
Case "eleven"
Text2.Text = "√Õœ ⁄‘—"
Case "twelve"
Text2.Text = "«À‰« ⁄‘—"
Case "thirteen"
Text2.Text = "À·«À ⁄‘—"
Case "fourteen"
Text2.Text = "√—»⁄ ⁄‘—"
Case "fifteen"
Text2.Text = "Œ„” ⁄‘—"
Case "sixteen"
Text2.Text = "”  ⁄‘—"
Case "seventeen"
Text2.Text = "”»⁄ ⁄‘—"
Case "eighteen"
Text2.Text = "À„«‰Ì ⁄‘—"
Case "nineteen"
Text2.Text = " ”⁄ ⁄‘—"
Case "twenty"
Text2.Text = "⁄‘—Ê‰"
Case "door"
Text2.Text = "»«»"
Case "window"
Text2.Text = "‰«›–…"

End Select
End Sub
